# Generated by Django 5.2.17 on 2026-08-23 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentDemographic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=50, unique=True)),
                ("code_module", models.CharField(max_length=10)),
                ("code_presentation", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=10)),
                ("region", models.CharField(max_length=50)),
                ("highest_education", models.CharField(max_length=100)),
                ("imd_band", models.CharField(max_length=20)),
                ("age_band", models.CharField(max_length=20)),
                ("num_of_prev_attempts", models.IntegerField(default=0)),
                ("studied_credits", models.IntegerField(default=0)),
                ("disability", models.CharField(max_length=5)),
                ("avg_assessment_score", models.FloatField(default=0.0)),
                ("vle_interaction_clicks", models.IntegerField(default=0)),
                ("final_result", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TeacherInsightFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("risk_score", models.FloatField(default=0.0)),
                ("ai_recommendation", models.TextField()),
                ("flagged_date", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ouled.studentdemographic",
                    ),
                ),
            ],
        ),
    ]
